flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: true
    old-locale: false
    network-uri: true
  pandoc-citeproc:
    bibutils: true
    embed_data_files: true
    unicode_collation: false
    test_citeproc: false
    debug: false
packages:
- '..'
extra-deps:
- 'hsb2hs-0.3.1'
- 'data-default-0.6.0'
- 'data-default-instances-base-0.1.0'
- 'preprocessor-tools-1.0.1'
- 'pandoc-citeproc-0.10'
resolver: lts-6.1
