flags: {}

resolver: lts-6.4
compiler: ghcjs-0.2.0.9006004_ghc-7.10.3

compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006004_ghc-7.10.3:
         url: "https://tolysz.org/ghcjs/lts-6.4-9006004.tar.gz"

allow-newer: true

packages:
- location: '.'
